/* Generated By:JavaCC: Do not edit this line. SQLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALL = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int SEMICOLON = 7;
  /** RegularExpression Id. */
  int EQUAL = 8;
  /** RegularExpression Id. */
  int POPEN = 9;
  /** RegularExpression Id. */
  int PCLOSE = 10;
  /** RegularExpression Id. */
  int SMALLER = 11;
  /** RegularExpression Id. */
  int BIGGER = 12;
  /** RegularExpression Id. */
  int ASPAS = 13;
  /** RegularExpression Id. */
  int SELECT = 14;
  /** RegularExpression Id. */
  int FROM = 15;
  /** RegularExpression Id. */
  int DISTINCT = 16;
  /** RegularExpression Id. */
  int WHERE = 17;
  /** RegularExpression Id. */
  int AND = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int NOT = 20;
  /** RegularExpression Id. */
  int IN = 21;
  /** RegularExpression Id. */
  int ORDERBY = 22;
  /** RegularExpression Id. */
  int ASC = 23;
  /** RegularExpression Id. */
  int DESC = 24;
  /** RegularExpression Id. */
  int AS = 25;
  /** RegularExpression Id. */
  int COUNT = 26;
  /** RegularExpression Id. */
  int LIKE = 27;
  /** RegularExpression Id. */
  int ID = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"*\"",
    "\",\"",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\"\\\'\"",
    "\"SELECT\"",
    "\"FROM\"",
    "\"DISTINCT\"",
    "\"WHERE\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"IN\"",
    "\"ORDER BY\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"AS\"",
    "\"COUNT\"",
    "\"LIKE\"",
    "<ID>",
  };

}
